drop view if exists kort.aggregateddata_from_all_missions;
drop view if exists kort.aggregateddata_from_all_validations;
drop view if exists kort.all_missions_with_promotions;
drop view if exists kort.all_validations_with_promotions;
drop view if exists kort.all_running_promotions;
drop view if exists kort.validations;
drop view if exists kort.all_fixes;
drop view if exists kort.errors;
drop view if exists kort.all_errors;
drop view if exists kort.error_types;
drop view if exists kort.user_model;
drop view if exists kort.highscore;
drop view if exists kort.language;
drop view if exists kort.relationtype;
drop view if exists kort.religion;
drop view if exists kort.select_answer;
drop view if exists kort.statistics;
drop view if exists kort.user_badges;

ALTER TABLE kort.fix ALTER COLUMN error_id TYPE bigint USING error_id::bigint;
ALTER TABLE kort.fix ALTER COLUMN osm_id TYPE bigint USING osm_id::bigint;