-- Insert badges                                                                                                                                                                             -- Insert badges
insert into kort.badge (badge_id, name, description, sorting) VALUES (1, 'highscore_place_1', 'Erster Rang in der Highscore erreicht', 110);
insert into kort.badge (badge_id, name, description, sorting) VALUES (2, 'highscore_place_2', 'Zweiter Rang in der Highscore erreicht', 120);
insert into kort.badge (badge_id, name, description, sorting) VALUES (3, 'highscore_place_3', 'Dritter Rang in der Highscore erreicht', 130);
insert into kort.badge (badge_id, name, description, sorting) VALUES (4, 'fix_count_100', '100 Aufträge erledigt', 210);
insert into kort.badge (badge_id, name, description, sorting) VALUES (5, 'fix_count_50', '50 Aufträge erledigt', 220);
insert into kort.badge (badge_id, name, description, sorting) VALUES (6, 'fix_count_10', '10 Aufträge erledigt', 230);
insert into kort.badge (badge_id, name, description, sorting) VALUES (7, 'verification_count_1000', '1000 Verifikationen getätigt', 310);
insert into kort.badge (badge_id, name, description, sorting) VALUES (8, 'verification_count_100', '100 Verifikationen getätigt', 320);
insert into kort.badge (badge_id, name, description, sorting) VALUES (9, 'verification_count_10', '10 Verifikationen getätigt', 330);
insert into kort.badge (badge_id, name, description, sorting) VALUES (10, 'diligent_fix_10_24', '10 Aufträge in 24h', 410);
insert into kort.badge (badge_id, name, description, sorting) VALUES (11, 'diligent_verification_10_24', '10 Verifikationen in 24h', 420);
insert into kort.badge (badge_id, name, description, sorting) VALUES (12, 'bugtype_motorway_ref', 'Einen Auftrag vom Typ Strassenbezeichner erledigt', 510);
insert into kort.badge (badge_id, name, description, sorting) VALUES (13, 'bugtype_religion', 'Einen Auftrag vom Typ Religion erledigt', 520);
insert into kort.badge (badge_id, name, description, sorting) VALUES (14, 'bugtype_poi_name', 'Einen Auftrag vom Typ POI ohne Namen erledigt', 530);
insert into kort.badge (badge_id, name, description, sorting) VALUES (15, 'bugtype_relation_type', 'Einen Auftrag vom Typ Relation ohne Typ erledigt', 540);
insert into kort.badge (badge_id, name, description, sorting) VALUES (16, 'bugtype_missing_maxspeed', 'Einen Auftrag vom Typ fehlendes Geschwindikeitslimit erledigt', 550);
insert into kort.badge (badge_id, name, description, sorting) VALUES (17, 'bugtype_language_unknown_unknown', 'Einen Auftrag vom Typ unbekannte Sprache erledigt', 560);
insert into kort.badge (badge_id, name, description, sorting) VALUES (18, 'bugtype_missing_track_type', 'Einen Auftrag vom Typ Strassentyp erledigt', 570);

-- Insert missing_track_types
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (1, 'missing_track_type', 'grade1', 'Asphalt, Beton oder Pflastersteine', 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (2, 'missing_track_type', 'grade2', 'Schotter', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (3, 'missing_track_type', 'grade3', 'Feinschotter-, Sand- oder Erdweg', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (4, 'missing_track_type', 'grade4', 'Weg mit Pflanzenwuchs entlang der Spurmitte', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (5, 'missing_track_type', 'grade5', 'Unbefestigter Weg', 150);

-- Insert religion
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (10, 'religion', 'buddhist','Buddhismus (Tempel)' , 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (11, 'religion', 'christian', 'Christentum (Kirche)', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (12, 'religion', 'hindu', 'Hinduismus (Tempel)', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (13, 'religion', 'jewish', 'Judentum (Synagoge)', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (14, 'religion', 'multifaith', 'Mehrere Religionen', 150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (15, 'religion', 'muslim', 'Islam (Moschee)', 160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (16, 'religion', 'pastafarian', 'Pastafarianismus', 170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (17, 'religion', 'shinto', 'Shinto (Schrein)', 180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (18, 'religion', 'sikh', 'Sikh (Gurdwara)', 190);

-- Insert language_unknown
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (100, 'language_unknown', 'ab', 'Abchasisch', 10);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (101, 'language_unknown', 'aa', 'Afar', 20);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (102, 'language_unknown', 'af', 'Afrikaans', 30);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (103, 'language_unknown', 'ak', 'Akan', 40);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (104, 'language_unknown', 'sq', 'Albanisch', 50);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (105, 'language_unknown', 'am', 'Amharisch', 60);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (106, 'language_unknown', 'ar', 'Arabisch', 70);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (107, 'language_unknown', 'an', 'Aragonesisch', 80);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (108, 'language_unknown', 'hy', 'Armenisch', 90);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (109, 'language_unknown', 'as', 'Assamesisch', 100);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (110, 'language_unknown', 'av', 'Awarisch', 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (111, 'language_unknown', 'ae', 'Avestisch', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (112, 'language_unknown', 'ay', 'Aymara', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (113, 'language_unknown', 'az', 'Aserbaidschanisch', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (114, 'language_unknown', 'bm', 'Bambara', 150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (115, 'language_unknown', 'ba', 'Bashkir', 160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (116, 'language_unknown', 'eu', 'Baskisch', 170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (117, 'language_unknown', 'be', 'Weissrussisch', 180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (118, 'language_unknown', 'bn', 'Bengalisch', 190);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (119, 'language_unknown', 'bh', 'Bihari', 200);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (120, 'language_unknown', 'bi', 'Bislama', 210);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (121, 'language_unknown', 'bs', 'Bosnisch', 220);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (122, 'language_unknown', 'br', 'Bretonisch', 230);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (123, 'language_unknown', 'bg', 'Bulgarisch', 240);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (124, 'language_unknown', 'my', 'Burmese', 250);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (125, 'language_unknown', 'ca', 'Katalanisch', 260);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (126, 'language_unknown', 'ch', 'Chamorro', 270);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (127, 'language_unknown', 'ce', 'Tschetschenisch', 280);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (128, 'language_unknown', 'ny', 'Chichewa', 290);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (129, 'language_unknown', 'zh', 'Chinesisch', 300);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (130, 'language_unknown', 'cv', 'Tschuwaschisch', 310);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (131, 'language_unknown', 'kw', 'Kornisch', 320);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (132, 'language_unknown', 'co', 'Korsisch', 330);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (133, 'language_unknown', 'cr', 'Cree', 340);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (134, 'language_unknown', 'hr', 'Kroatisch', 350);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (135, 'language_unknown', 'cs', 'Tschechisch', 360);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (136, 'language_unknown', 'da', 'Dänisch', 370);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (137, 'language_unknown', 'dv', 'Divehi', 380);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (138, 'language_unknown', 'nl', 'Holländisch', 390);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (139, 'language_unknown', 'dz', 'Dzongkha', 400);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (140, 'language_unknown', 'en', 'Englisch', 410);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (141, 'language_unknown', 'eo', 'Esperanto', 420);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (142, 'language_unknown', 'et', 'Estnisch', 430);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (143, 'language_unknown', 'ee', 'Ewe', 440);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (144, 'language_unknown', 'fo', 'Färöisch', 450);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (145, 'language_unknown', 'fj', 'Fidschi', 460);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (146, 'language_unknown', 'fi', 'Finnisch', 470);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (147, 'language_unknown', 'fr', 'Französisch', 480);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (148, 'language_unknown', 'ff', 'Fulfulde', 490);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (149, 'language_unknown', 'gl', 'Galicisch', 500);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (150, 'language_unknown', 'ka', 'Georgian', 510);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (151, 'language_unknown', 'de', 'Deutsch', 1);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (152, 'language_unknown', 'el', 'Griechisch', 530);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (153, 'language_unknown', 'gn', 'Guaraní', 540);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (154, 'language_unknown', 'gu', 'Gujarati', 550);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (155, 'language_unknown', 'ht', 'Haitianisch', 560);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (156, 'language_unknown', 'ha', 'Hausa', 570);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (157, 'language_unknown', 'he', 'Hebräisch', 580);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (158, 'language_unknown', 'hz', 'Herero', 590);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (159, 'language_unknown', 'hi', 'Hindi', 600);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (160, 'language_unknown', 'ho', 'Hiri Motu', 610);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (161, 'language_unknown', 'hu', 'Ungarisch', 620);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (162, 'language_unknown', 'ia', 'Interlingua', 630);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (163, 'language_unknown', 'id', 'Malaiisch', 640);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (164, 'language_unknown', 'ie', 'Interlingue', 650);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (165, 'language_unknown', 'ga', 'Irisch', 660);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (166, 'language_unknown', 'ig', 'Igbo', 670);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (167, 'language_unknown', 'ik', 'Inupiaq', 680);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (168, 'language_unknown', 'io', 'Ido', 690);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (169, 'language_unknown', 'is', 'Isländisch', 700);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (170, 'language_unknown', 'it', 'Italienisch', 710);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (171, 'language_unknown', 'iu', 'Inuktitut', 720);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (172, 'language_unknown', 'ja', 'Japanisch', 730);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (173, 'language_unknown', 'jv', 'Javanisch', 740);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (174, 'language_unknown', 'kl', 'Grönländisch', 750);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (175, 'language_unknown', 'kn', 'Kannada', 760);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (176, 'language_unknown', 'kr', 'Kanuri', 770);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (177, 'language_unknown', 'ks', 'Kashmiri', 780);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (178, 'language_unknown', 'kk', 'Kasachisch', 790);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (179, 'language_unknown', 'km', 'Khmer', 800);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (180, 'language_unknown', 'ki', 'Kikuyu', 810);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (181, 'language_unknown', 'rw', 'Kinyarwanda', 820);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (182, 'language_unknown', 'ky', 'Kirgisisch', 830);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (183, 'language_unknown', 'kv', 'Komi', 840);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (184, 'language_unknown', 'kg', 'Kikongo', 850);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (185, 'language_unknown', 'ko', 'Koreanisch', 860);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (186, 'language_unknown', 'ku', 'Kurdisch', 870);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (187, 'language_unknown', 'kj', 'Kwanyama, Kuanyama', 880);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (188, 'language_unknown', 'la', 'Lateinisch', 890);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (189, 'language_unknown', 'lb', 'Luxemburgisch', 900);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (190, 'language_unknown', 'lg', 'Ganda', 910);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (191, 'language_unknown', 'li', 'Limburgisch', 920);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (192, 'language_unknown', 'ln', 'Lingala', 930);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (193, 'language_unknown', 'lo', 'Laotisch', 940);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (194, 'language_unknown', 'lt', 'Litauisch', 950);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (195, 'language_unknown', 'lu', 'Tschiluba', 960);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (196, 'language_unknown', 'lv', 'Lettisch', 970);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (197, 'language_unknown', 'gv', 'Manx', 980);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (198, 'language_unknown', 'mk', 'Mazedonisch', 990);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (199, 'language_unknown', 'mg', 'Malagasy', 1000);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (200, 'language_unknown', 'ms', 'Malay', 1010);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (201, 'language_unknown', 'ml', 'Malayalam', 1020);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (202, 'language_unknown', 'mt', 'Maltesisch', 1030);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (203, 'language_unknown', 'mi', 'Māori', 1040);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (204, 'language_unknown', 'mr', 'Marathi', 1050);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (205, 'language_unknown', 'mh', 'Marshallesisch', 1060);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (206, 'language_unknown', 'mn', 'Mongolisch', 1070);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (207, 'language_unknown', 'na', 'Nauruisch', 1080);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (208, 'language_unknown', 'nv', 'Navajo, Navaho', 1090);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (210, 'language_unknown', 'nd', 'isiNdebele', 1110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (211, 'language_unknown', 'ne', 'Nepali', 1120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (212, 'language_unknown', 'ng', 'Ndonga', 1130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (209, 'language_unknown', 'nb', 'Norwegisch (Bokmål)', 1139);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (213, 'language_unknown', 'nn', 'Norwegisch (Nynorsk)', 1140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (214, 'language_unknown', 'no', 'Norwegisch', 1150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (215, 'language_unknown', 'ii', 'Nuosu', 1160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (216, 'language_unknown', 'nr', 'Süd-Ndebele', 1170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (217, 'language_unknown', 'oc', 'Okzitanisch', 1180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (218, 'language_unknown', 'oj', 'Ojibwe', 1190);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (219, 'language_unknown', 'cu', 'Altkirchenslawisch', 1200);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (220, 'language_unknown', 'om', 'Oromo', 1210);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (221, 'language_unknown', 'or', 'Oriya', 1220);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (222, 'language_unknown', 'os', 'Ossetisch', 1230);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (223, 'language_unknown', 'pa', 'Panjabi', 1240);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (224, 'language_unknown', 'pi', 'Pāli', 1250);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (225, 'language_unknown', 'fa', 'Persisch', 1260);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (226, 'language_unknown', 'pl', 'Polnisch', 1270);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (227, 'language_unknown', 'ps', 'Pashto, Pushto', 1280);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (228, 'language_unknown', 'pt', 'Portugiesisch', 1290);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (229, 'language_unknown', 'qu', 'Quechua', 1300);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (230, 'language_unknown', 'rm', 'Rätoromanisch', 1310);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (231, 'language_unknown', 'rn', 'Kirundi', 1320);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (232, 'language_unknown', 'ro', 'Rumänisch', 1330);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (233, 'language_unknown', 'ru', 'Russisch', 1340);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (234, 'language_unknown', 'sa', 'Sanskrit', 1350);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (235, 'language_unknown', 'sc', 'Sardisch', 1360);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (236, 'language_unknown', 'sd', 'Sindhi', 1370);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (237, 'language_unknown', 'se', 'Northern Sami', 1380);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (238, 'language_unknown', 'sm', 'Samoan', 1390);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (239, 'language_unknown', 'sg', 'Sango', 1400);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (240, 'language_unknown', 'sr', 'Serbisch', 1410);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (241, 'language_unknown', 'gd', 'Schottisch-Gälisch', 1420);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (242, 'language_unknown', 'sn', 'Shona', 1430);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (243, 'language_unknown', 'si', 'Sinhala, Sinhalese', 1440);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (244, 'language_unknown', 'sk', 'Slowakisch', 1450);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (245, 'language_unknown', 'sl', 'Slowenisch', 1460);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (246, 'language_unknown', 'so', 'Somali', 1470);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (247, 'language_unknown', 'st', 'Sesotho', 1480);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (248, 'language_unknown', 'es', 'Spanisch', 1490);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (249, 'language_unknown', 'su', 'Sudanesisch', 1500);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (250, 'language_unknown', 'sw', 'Swahili', 1510);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (251, 'language_unknown', 'ss', 'Siswati', 1520);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (252, 'language_unknown', 'sv', 'Schwedisch', 1530);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (253, 'language_unknown', 'ta', 'Tamil', 1540);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (254, 'language_unknown', 'te', 'Telugu', 1550);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (255, 'language_unknown', 'tg', 'Tadschikisch', 1560);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (256, 'language_unknown', 'th', 'Thailändisch', 1570);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (257, 'language_unknown', 'ti', 'Tigrinya', 1580);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (258, 'language_unknown', 'bo', 'Tibetisch', 1590);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (259, 'language_unknown', 'tk', 'Turkmenisch', 1600);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (260, 'language_unknown', 'tl', 'Tagalog', 1610);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (261, 'language_unknown', 'tn', 'Setswana', 1620);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (262, 'language_unknown', 'to', 'Tongaisch', 1630);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (263, 'language_unknown', 'tr', 'Türkisch', 1640);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (264, 'language_unknown', 'ts', 'Xitsonga', 1650);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (265, 'language_unknown', 'tt', 'Tatarisch', 1660);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (266, 'language_unknown', 'tw', 'Akan', 1670);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (267, 'language_unknown', 'ty', 'Tahitianisch', 1680);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (268, 'language_unknown', 'ug', 'Uigurisch', 1690);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (269, 'language_unknown', 'uk', 'Ukrainisch', 1700);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (270, 'language_unknown', 'ur', 'Urdu', 1710);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (271, 'language_unknown', 'uz', 'Uzbekisch', 1720);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (272, 'language_unknown', 've', 'Tshivenda', 1730);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (273, 'language_unknown', 'vi', 'Vietnamesisch', 1740);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (274, 'language_unknown', 'vo', 'Volapük', 1750);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (275, 'language_unknown', 'wa', 'Wallonisch', 1760);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (276, 'language_unknown', 'cy', 'Walisisch', 1770);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (277, 'language_unknown', 'wo', 'Wolof', 1780);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (278, 'language_unknown', 'fy', 'Westfriesisch', 1790);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (279, 'language_unknown', 'xh', 'Xhosa', 1800);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (280, 'language_unknown', 'yi', 'Jiddisch', 1810);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (281, 'language_unknown', 'yo', 'Yoruba', 1820);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (282, 'language_unknown', 'za', 'Zhuang, Chuang', 1830);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (283, 'language_unknown', 'zu', 'Zulu', 1840);