-- Insert badges
insert into kort.badge (badge_id, name, description, sorting) VALUES (1, 'highscore_place_1', 'Erster Rang in der Highscore erreicht', 110);
insert into kort.badge (badge_id, name, description, sorting) VALUES (2, 'highscore_place_2', 'Zweiter Rang in der Highscore erreicht', 120);
insert into kort.badge (badge_id, name, description, sorting) VALUES (3, 'highscore_place_3', 'Dritter Rang in der Highscore erreicht', 130);
insert into kort.badge (badge_id, name, description, sorting) VALUES (4, 'fix_count_100', '100 Aufträge erledigt', 210);
insert into kort.badge (badge_id, name, description, sorting) VALUES (5, 'fix_count_50', '50 Aufträge erledigt', 220);
insert into kort.badge (badge_id, name, description, sorting) VALUES (6, 'fix_count_10', '10 Aufträge erledigt', 230);
insert into kort.badge (badge_id, name, description, sorting) VALUES (7, 'verification_count_1000', '1000 Verifikationen getätigt', 310);
insert into kort.badge (badge_id, name, description, sorting) VALUES (8, 'verification_count_100', '100 Verifikationen getätigt', 320);
insert into kort.badge (badge_id, name, description, sorting) VALUES (9, 'verification_count_10', '10 Verifikationen getätigt', 330);
insert into kort.badge (badge_id, name, description, sorting) VALUES (10, 'diligent_fix_10_24', '10 Aufträge in 24h', 410);
insert into kort.badge (badge_id, name, description, sorting) VALUES (11, 'diligent_verification_10_24', '10 Verifikationen in 24h', 420);
insert into kort.badge (badge_id, name, description, sorting) VALUES (12, 'bugtype_motorway_ref', 'Einen Auftrag vom Typ Strassenbezeichner erledigt', 510);
insert into kort.badge (badge_id, name, description, sorting) VALUES (13, 'bugtype_religion', 'Einen Auftrag vom Typ Religion erledigt', 520);
insert into kort.badge (badge_id, name, description, sorting) VALUES (14, 'bugtype_poi_name', 'Einen Auftrag vom Typ POI ohne Namen erledigt', 530);
insert into kort.badge (badge_id, name, description, sorting) VALUES (15, 'bugtype_relation_type', 'Einen Auftrag vom Typ Relation ohne Typ erledigt', 540);
insert into kort.badge (badge_id, name, description, sorting) VALUES (16, 'bugtype_missing_maxspeed', 'Einen Auftrag vom Typ fehlendes Geschwindikeitslimit erledigt', 550);
insert into kort.badge (badge_id, name, description, sorting) VALUES (17, 'bugtype_language_unknown', 'Einen Auftrag vom Typ unbekannte Sprache erledigt', 560);
insert into kort.badge (badge_id, name, description, sorting) VALUES (18, 'bugtype_missing_track_type', 'Einen Auftrag vom Typ Strassentyp erledigt', 570);

-- Insert tracktypes
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (1, 'tracktype', 'grade1', 'Asphalt, Beton oder Pflastersteine', 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (2, 'tracktype', 'grade2', 'Schotter', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (3, 'tracktype', 'grade3', 'Feinschotter-, Sand- oder Erdweg', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (4, 'tracktype', 'grade4', 'Weg mit Pflanzenwuchs entlang der Spurmitte', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (5, 'tracktype', 'grade5', 'Unbefestigter Weg', 150);

-- Insert religion
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (10,  'religion', 'buddhist','Buddhismus (Tempel)' , 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (11,  'religion', 'christian', 'Christentum (Kirche)', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (12, 'religion', 'hindu', 'Hinduismus (Tempel)', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (13, 'religion', 'jewish', 'Judentum (Synagoge)', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (14, 'religion', 'multifaith', 'Mehrere Religionen', 150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (15, 'religion', 'muslim', 'Islam (Moschee)'), 160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (16, 'religion', 'pastafarian', 'Pastafarianismus', 170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (17, 'religion', 'shinto', 'Shinto (Schrein)', 180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (18, 'religion', 'sikh', 'Sikh (Gurdwara)', 190);

-- Insert language
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (100,'language', 'ab', 'Abchasisch', 10);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (101,'language', 'aa', 'Afar', 20);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (102,'language', 'af', 'Afrikaans', 30);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (103,'language', 'ak', 'Akan', 40);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (104,'language', 'sq', 'Albanisch', 50);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (105,'language', 'am', 'Amharisch', 60);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (106,'language', 'ar', 'Arabisch', 70);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (107,'language', 'an', 'Aragonesisch', 80);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (108,'language', 'hy', 'Armenisch', 90);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (109,'language', 'as', 'Assamesisch', 100);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (110,'language', 'av', 'Awarisch', 110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (111,'language', 'ae', 'Avestisch', 120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (112,'language', 'ay', 'Aymara', 130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (113,'language', 'az', 'Aserbaidschanisch', 140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (114,'language', 'bm', 'Bambara', 150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (115,'language', 'ba', 'Bashkir', 160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (116,'language', 'eu', 'Baskisch', 170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (117,'language', 'be', 'Weissrussisch', 180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (118,'language', 'bn', 'Bengalisch', 190);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (119,'language', 'bh', 'Bihari', 200);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (120,'language', 'bi', 'Bislama', 210);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (121,'language', 'bs', 'Bosnisch', 220);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (122,'language', 'br', 'Bretonisch', 230);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (123,'language', 'bg', 'Bulgarisch', 240);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (124,'language', 'my', 'Burmese', 250);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (125,'language', 'ca', 'Katalanisch', 260);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (126,'language', 'ch', 'Chamorro', 270);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (127,'language', 'ce', 'Tschetschenisch', 280);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (128,'language', 'ny', 'Chichewa', 290);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (129,'language', 'zh', 'Chinesisch', 300);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (130,'language', 'cv', 'Tschuwaschisch', 310);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (131,'language', 'kw', 'Kornisch', 320);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (132,'language', 'co', 'Korsisch', 330);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (133,'language', 'cr', 'Cree', 340);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (134,'language', 'hr', 'Kroatisch', 350);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (135,'language', 'cs', 'Tschechisch', 360);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (136,'language', 'da', 'Dänisch', 370);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (137,'language', 'dv', 'Divehi', 380);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (138,'language', 'nl', 'Holländisch', 390);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (139,'language', 'dz', 'Dzongkha', 400);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (140,'language', 'en', 'Englisch', 410);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (141,'language', 'eo', 'Esperanto', 420);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (142,'language', 'et', 'Estnisch', 430);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (143,'language', 'ee', 'Ewe', 440);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (144,'language', 'fo', 'Färöisch', 450);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (145,'language', 'fj', 'Fidschi', 460);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (146,'language', 'fi', 'Finnisch', 470);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (147,'language', 'fr', 'Französisch', 480);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (148,'language', 'ff', 'Fulfulde', 490);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (149,'language', 'gl', 'Galicisch', 500);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (150,'language', 'ka', 'Georgian', 510);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (151,'language', 'de', 'Deutsch', 1);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (152,'language', 'el', 'Griechisch', 530);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (153,'language', 'gn', 'Guaraní', 540);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (154,'language', 'gu', 'Gujarati', 550);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (155,'language', 'ht', 'Haitianisch', 560);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (156,'language', 'ha', 'Hausa', 570);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (157,'language', 'he', 'Hebräisch', 580);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (158,'language', 'hz', 'Herero', 590);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (159,'language', 'hi', 'Hindi', 600);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (160,'language', 'ho', 'Hiri Motu', 610);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (161,'language', 'hu', 'Ungarisch', 620);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (162,'language', 'ia', 'Interlingua', 630);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (163,'language', 'id', 'Malaiisch', 640);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (164,'language', 'ie', 'Interlingue', 650);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (165,'language', 'ga', 'Irisch', 660);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (166,'language', 'ig', 'Igbo', 670);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (167,'language', 'ik', 'Inupiaq', 680);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (168,'language', 'io', 'Ido', 690);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (169,'language', 'is', 'Isländisch', 700);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (170,'language', 'it', 'Italienisch', 710);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (171,'language', 'iu', 'Inuktitut', 720);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (172,'language', 'ja', 'Japanisch', 730);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (173,'language', 'jv', 'Javanisch', 740);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (174,'language', 'kl', 'Grönländisch', 750);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (175,'language', 'kn', 'Kannada', 760);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (176,'language', 'kr', 'Kanuri', 770);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (177,'language', 'ks', 'Kashmiri', 780);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (178,'language', 'kk', 'Kasachisch', 790);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (179,'language', 'km', 'Khmer', 800);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (180,'language', 'ki', 'Kikuyu', 810);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (181,'language', 'rw', 'Kinyarwanda', 820);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (182,'language', 'ky', 'Kirgisisch', 830);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (183,'language', 'kv', 'Komi', 840);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (184,'language', 'kg', 'Kikongo', 850);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (185,'language', 'ko', 'Koreanisch', 860);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (186,'language', 'ku', 'Kurdisch', 870);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (187,'language', 'kj', 'Kwanyama, Kuanyama', 880);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (188,'language', 'la', 'Lateinisch', 890);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (189,'language', 'lb', 'Luxemburgisch', 900);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (190,'language', 'lg', 'Ganda', 910);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (191,'language', 'li', 'Limburgisch', 920);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (192,'language', 'ln', 'Lingala', 930);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (193,'language', 'lo', 'Laotisch', 940);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (194,'language', 'lt', 'Litauisch', 950);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (195,'language', 'lu', 'Tschiluba', 960);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (196,'language', 'lv', 'Lettisch', 970);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (197,'language', 'gv', 'Manx', 980);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (198,'language', 'mk', 'Mazedonisch', 990);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (199,'language', 'mg', 'Malagasy', 1000);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (200,'language', 'ms', 'Malay', 1010);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (201,'language', 'ml', 'Malayalam', 1020);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (202,'language', 'mt', 'Maltesisch', 1030);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (203,'language', 'mi', 'Māori', 1040);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (204,'language', 'mr', 'Marathi', 1050);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (205,'language', 'mh', 'Marshallesisch', 1060);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (206,'language', 'mn', 'Mongolisch', 1070);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (207,'language', 'na', 'Nauruisch', 1080);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (208,'language', 'nv', 'Navajo, Navaho', 1090);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (210,'language', 'nd', 'isiNdebele', 1110);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (211,'language', 'ne', 'Nepali', 1120);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (212,'language', 'ng', 'Ndonga', 1130);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (209,'language', 'nb', 'Norwegisch (Bokmål)', 1139);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (213,'language', 'nn', 'Norwegisch (Nynorsk)', 1140);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (214,'language', 'no', 'Norwegisch', 1150);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (215,'language', 'ii', 'Nuosu', 1160);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (216,'language', 'nr', 'Süd-Ndebele', 1170);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (217,'language', 'oc', 'Okzitanisch', 1180);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (218,'language', 'oj', 'Ojibwe', 1190);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (219,'language', 'cu', 'Altkirchenslawisch', 1200);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (220,'language', 'om', 'Oromo', 1210);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (221,'language', 'or', 'Oriya', 1220);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (222,'language', 'os', 'Ossetisch', 1230);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (223,'language', 'pa', 'Panjabi', 1240);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (224,'language', 'pi', 'Pāli', 1250);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (225,'language', 'fa', 'Persisch', 1260);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (226,'language', 'pl', 'Polnisch', 1270);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (227,'language', 'ps', 'Pashto, Pushto', 1280);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (228,'language', 'pt', 'Portugiesisch', 1290);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (229,'language', 'qu', 'Quechua', 1300);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (230,'language', 'rm', 'Rätoromanisch', 1310);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (231,'language', 'rn', 'Kirundi', 1320);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (232,'language', 'ro', 'Rumänisch', 1330);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (233,'language', 'ru', 'Russisch', 1340);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (234,'language', 'sa', 'Sanskrit', 1350);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (235,'language', 'sc', 'Sardisch', 1360);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (236,'language', 'sd', 'Sindhi', 1370);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (237,'language', 'se', 'Northern Sami', 1380);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (238,'language', 'sm', 'Samoan', 1390);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (239,'language', 'sg', 'Sango', 1400);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (240,'language', 'sr', 'Serbisch', 1410);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (241,'language', 'gd', 'Schottisch-Gälisch', 1420);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (242,'language', 'sn', 'Shona', 1430);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (243,'language', 'si', 'Sinhala, Sinhalese', 1440);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (244,'language', 'sk', 'Slowakisch', 1450);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (245,'language', 'sl', 'Slowenisch', 1460);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (246,'language', 'so', 'Somali', 1470);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (247,'language', 'st', 'Sesotho', 1480);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (248,'language', 'es', 'Spanisch', 1490);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (249,'language', 'su', 'Sudanesisch', 1500);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (250,'language', 'sw', 'Swahili', 1510);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (251,'language', 'ss', 'Siswati', 1520);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (252,'language', 'sv', 'Schwedisch', 1530);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (253,'language', 'ta', 'Tamil', 1540);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (254,'language', 'te', 'Telugu', 1550);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (255,'language', 'tg', 'Tadschikisch', 1560);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (256,'language', 'th', 'Thailändisch', 1570);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (257,'language', 'ti', 'Tigrinya', 1580);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (258,'language', 'bo', 'Tibetisch', 1590);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (259,'language', 'tk', 'Turkmenisch', 1600);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (260,'language', 'tl', 'Tagalog', 1610);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (261,'language', 'tn', 'Setswana', 1620);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (262,'language', 'to', 'Tongaisch', 1630);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (263,'language', 'tr', 'Türkisch', 1640);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (264,'language', 'ts', 'Xitsonga', 1650);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (265,'language', 'tt', 'Tatarisch', 1660);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (266,'language', 'tw', 'Akan', 1670);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (267,'language', 'ty', 'Tahitianisch', 1680);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (268,'language', 'ug', 'Uigurisch', 1690);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (269,'language', 'uk', 'Ukrainisch', 1700);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (270,'language', 'ur', 'Urdu', 1710);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (271,'language', 'uz', 'Uzbekisch', 1720);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (272,'language', 've', 'Tshivenda', 1730);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (273,'language', 'vi', 'Vietnamesisch', 1740);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (274,'language', 'vo', 'Volapük', 1750);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (275,'language', 'wa', 'Wallonisch', 1760);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (276,'language', 'cy', 'Walisisch', 1770);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (277,'language', 'wo', 'Wolof', 1780);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (278,'language', 'fy', 'Westfriesisch', 1790);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (279,'language', 'xh', 'Xhosa', 1800);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (280,'language', 'yi', 'Jiddisch', 1810);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (281,'language', 'yo', 'Yoruba', 1820);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (282,'language', 'za', 'Zhuang, Chuang', 1830);
insert into kort.answer (answer_id, type, value, title, sorting) VALUES (283,'language', 'zu', 'Zulu', 1840);